blank_issues_enabled: true
contact_links:
  - name: Bot Invite Link
    url: https://discordapp.com/oauth2/authorize?client_id=1102551839674740737&scope=bot&permissions=1099780064256
    about: Click this link to invite the bot to your server
